if master or patch do not wait on test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -53,26 +53,35 @@ jobs:
       - run:
           name: Bot Test
           command: |
-            message="I am online for about 8 minutes for testing\n"
-            curl -X POST \
-                  -d chat_id=${GROUP_TELEGRAM_ID} \
-                  -d text="$(echo -e ${message})" \
-                  https://api.telegram.org/bot${RTB_TELEGRAM_BOT_TOKEN}/sendMessage
-            
-            sed -i 's/${RTB_TELEGRAM_BOT_TOKEN}/'${RTB_TELEGRAM_BOT_TOKEN}/ config.json
-            
-            #Bot will run for 8 min for testing
-            #8 min because circleCi will automatically fail on timeout in 10 min
-            timeout 480 node ${BOT_NAME} || true
+            if [[ ${CIRCLE_BRANCH} != "master" ]] || [[ ${CIRCLE_BRANCH} != "patch" ]]; then
+              message="I am online for about 8 minutes for testing\n"
+              curl -X POST \
+                    -d chat_id=${GROUP_TELEGRAM_ID} \
+                    -d text="$(echo -e ${message})" \
+                    https://api.telegram.org/bot${RTB_TELEGRAM_BOT_TOKEN}/sendMessage
+              
+              sed -i 's/${RTB_TELEGRAM_BOT_TOKEN}/'${RTB_TELEGRAM_BOT_TOKEN}/ config.json
+              
+              #Bot will run for 8 min for testing
+              #8 min because circleCi will automatically fail on timeout in 10 min
+              timeout 480 node ${BOT_NAME} || true
 
-            message="I am shutting down now\n"
-            message+="Thanks for testing!\n\n"
-            message+="If you want to run the same test, trigger the following url again...\n"
-            message+="https://circleci.com/gh/realtime-bus/node-telegram-bot/${CIRCLE_BUILD_NUM}"
-            curl -X POST \
-                  -d chat_id=${GROUP_TELEGRAM_ID} \
-                  -d text="$(echo -e ${message})" \
-                  https://api.telegram.org/bot${RTB_TELEGRAM_BOT_TOKEN}/sendMessage
+              message="I am shutting down now\n"
+              message+="Thanks for testing!\n\n"
+              message+="If you want to run the same test, trigger the following url again...\n"
+              message+="https://circleci.com/gh/realtime-bus/node-telegram-bot/${CIRCLE_BUILD_NUM}"
+              curl -X POST \
+                    -d chat_id=${GROUP_TELEGRAM_ID} \
+                    -d text="$(echo -e ${message})" \
+                    https://api.telegram.org/bot${RTB_TELEGRAM_BOT_TOKEN}/sendMessage
+            else
+              message="Test passed on branch: ${CIRCLE_BRANCH}"
+              curl -X POST \
+                    -d chat_id=${GROUP_TELEGRAM_ID} \
+                    -d text="$(echo -e ${message})" \
+                    https://api.telegram.org/bot${RTB_TELEGRAM_BOT_TOKEN}/sendMessage
+            fi
+
   prepare-dev-deploy:
     <<: *defaults
     steps:
